name: Laravel

on:
  push:
  pull_request:

jobs:
  laravel-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - "8.0"
        experimental:
          - false

    name: PHP${{ matrix.php }} on ${{ matrix.os }}

    services:
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "locked"
          composer-options: "--prefer-dist --no-cache"
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Prepare storage
        run: php artisan storage:link
      - name: Run Tests
        run: php artisan test
